// CHoferes

export const LOAD = "LOAD";
export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const CLEAR = "CLEAR";
export const LOAD_PENDING = "LOAD_PENDING";


// Omnibus
export const LOAD_OMNIBUS = "LOAD_OMNIBUS";
export const CREATE_OMNIBUS = "CREATE_OMNIBUS";
export const UPDATE_OMNIBUS = "UPDATE_OMNIBUS";
export const DELETE_OMNIBUS = "DELETE_OMNIBUS";
export const CLEAR_OMNIBUS = "CLEAR_OMNIBUS";
export const OMNIBUS_MAS_VIAJES = "OMNIBUS_MAS_VIAJES";
export const OMNIBUS_TALLER = "OMNIBUS_TALLER";
export const OMNIBUS_DISPONIBLES = "OMNIBUS_DISPONIBLES";
export const LOAD_PENDING_OMNIBUS = "LOAD_PENDING_OMNIBUS";

//Viajes
export const LOAD_VIAJES = "LOAD_VIAJES";
export const CREATE_VIAJES = "CREATE_VIAJES";
export const UPDATE_VIAJES = "UPDATE_VIAJES";
export const DELETE_VIAJES = "DELETE_VIAJES";
export const CLEAR_VIAJES = "CLEAR_VIAJES";
export const LOAD_DESTINOS = "LOAD_DESTINOS";
export const LOAD_VIAJES_PENDING = "LOAD_VIAJES_PENDING";


//User

export const ISAUTENTICATE = "ISAUTENTICATE";
export const ISAUTENTICATEError = "ISAUTENTICATEError";


//RESERVACION

export const LOAD_RESERVACIONES = "LOAD_RESERVACIONES";
export const DELETE_RESERVACIONES = "DELETE_RESERVACIONES";
export const VER_VIAJEROS = "VER_VIAJEROS";
export const REALIZAR_RESERVACION = "REALIZAR_RESERVACION" 
export const CANT_PERSONAS_A_VIAJAR = "CANT_PERSONAS_A_VIAJAR"; 
export const LOAD_PENDING_RESERVACIONES = "LOAD_PENDING_RESERVACIONES";